import './globals.css'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";

import { Nunito_Sans, Varela_Round } from 'next/font/google'
import { ReduxProvider } from '@/components';
import localFont from 'next/font/local'

const futura_now_var = localFont({
  src: '../fonts/futura-now-var.ttf',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={futura_now_var.className+` text-[15px] leading-6 font-[500] text-black`}>{children}</body>
      </ReduxProvider>
    </html>
  )
}
