import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const nunito_sans = Nunito_Sans({
  subsets: ['latin'],
  weight: '300',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`text-xs font-[500] text-black`}>{children}</body>
    </html>
  )
}
