import './globals.css'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";

import { Nunito_Sans } from 'next/font/google'
import { ReduxProvider } from '@/components';

const nunito_sans = Nunito_Sans({
  subsets: ['latin'],
  weight: '300',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`text-xs font-[500] text-black`}>{children}</body>
      </ReduxProvider>
    </html>
  )
}
